import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';
import { getUser } from '@/service/getUser';
import { Navbar } from '@/components/shared/Navbar';
import { Footer } from '@/components/shared/Footer';

export const metadata: Metadata = {
  title: 'Fix It Now - NextApp',
  description: 'Generated by NextApp',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-serif')}>
      <body>
        {/* Navbar */}
        <Navbar user={user} />

        <main>{children}</main>

        {/* Footer */}
        <Footer />

        {/* Toaster */}
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
